import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { ResourceData, GeneratedContent } from '../lib/teacherpages/types';

// Register fonts if needed
Font.register({
  family: 'Roboto',
  src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf',
});

// Create styles
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 30,
    fontFamily: 'Roboto',
  },
  header: {
    marginBottom: 20,
    textAlign: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#0C41FF',
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 5,
  },
  instructions: {
    fontSize: 12,
    marginBottom: 20,
    padding: 10,
    backgroundColor: '#f8f9fa',
    borderRadius: 5,
  },
  questionSection: {
    marginBottom: 15,
  },
  questionNumber: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: '#333333',
  },
  questionText: {
    fontSize: 12,
    marginBottom: 10,
    lineHeight: 1.4,
  },
  answerSection: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#f0f4ff',
    borderRadius: 5,
  },
  answerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#0C41FF',
  },
  answerItem: {
    fontSize: 12,
    marginBottom: 5,
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#666666',
  },
});

interface WorksheetTemplateProps {
  resourceData: ResourceData;
  generatedContent: GeneratedContent;
}

const WorksheetTemplate: React.FC<WorksheetTemplateProps> = ({ resourceData, generatedContent }) => {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>
            {generatedContent.worksheetTitle || `${resourceData.subject} Worksheet`}
          </Text>
          <Text style={styles.subtitle}>
            {resourceData.level} • Grade {resourceData.grade} • {resourceData.subject}
          </Text>
          <Text style={styles.subtitle}>
            Topic: {resourceData.topic}
          </Text>
          <Text style={styles.subtitle}>
            Difficulty Level: {resourceData.difficulty || 3}/5
          </Text>
        </View>

        {/* Instructions */}
        {generatedContent.instructions && (
          <View style={styles.instructions}>
            <Text style={styles.questionText}>
              <Text style={{ fontWeight: 'bold' }}>Instructions: </Text>
              {generatedContent.instructions}
            </Text>
          </View>
        )}

        {/* Questions */}
        {Array.from({ length: 5 }, (_, i) => i + 1).map((questionNum) => {
          const questionKey = `question${questionNum}`;
          const questionText = generatedContent[questionKey];
          
          if (!questionText) return null;
          
          return (
            <View key={questionNum} style={styles.questionSection}>
              <Text style={styles.questionNumber}>
                Question {questionNum}:
              </Text>
              <Text style={styles.questionText}>
                {questionText}
              </Text>
            </View>
          );
        })}

        {/* Answer Key */}
        <View style={styles.answerSection}>
          <Text style={styles.answerTitle}>Answer Key</Text>
          {Array.from({ length: 5 }, (_, i) => i + 1).map((answerNum) => {
            const answerKey = `answer${answerNum}`;
            const answerText = generatedContent[answerKey];
            
            if (!answerText) return null;
            
            return (
              <Text key={answerNum} style={styles.answerItem}>
                <Text style={{ fontWeight: 'bold' }}>{answerNum}. </Text>
                {answerText}
              </Text>
            );
          })}
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by Teacher Pages • {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
};

export default WorksheetTemplate;
